const express = require('express');
const router = express.Router();
const verifyjwt = require('../middleware/verifyjwt');
const paymentscontroller = require('../controllers/paymentscontroller');
router.use(verifyjwt);
router.route('/create-checkout-session').post(paymentscontroller.createCheckoutSession);
router.route("/verify-payment").get(paymentscontroller.verifyPayment);
// router.route("/create-order").post(paymentscontroller.createOrder);
router.route("/").get(paymentscontroller.sendAdminOrders);
router.route("/confirm-order").post(paymentscontroller.confirmOrder);
router.route("/:id").get(paymentscontroller.getEachDetailedOrder);
module.exports = router;
